### PR TITLE
Update directory.txt

### PR DESCRIPTION
**Pull request by intothebeans**

### CODE REVIEW

**Comment by dyfer** [comment]
Hello @intothebeans 
Your quark is missing a quark file.
Also, please note, in order to install a quark, it's enough to do `Quarks.install("<url>")`; there's no need to download a release zip. Moreover, if this quark would be added to the `directory.txt`, it would be installed straight from the GH repo, not from the release zip. Having a release zip is rather non-standard for a quarks (but is necessary for extensions that include binary/executable files).
If you want to keep your current way of releasing and installing your quark, then it shouldn't be added to `directory.txt` IMO.

**Comment by intothebeans** [comment]
Thanks for the info. Will update.

**Comment by intothebeans** [comment]
I updated my repository to add a quark file and remove the release. I was confusing quarks and extensions. Would appreciate another look. Thanks!

**Comment by dyfer** [comment]
Thanks, this looks fine now.
Just to be clear, having tags is totally fine, and actually that's a way to keep track of the quark's version (the tags will show up as a version to install in `Quarks.gui`. It's just that creating a zip to download from the release page does not make sense for quarks.

**Pull request merged**
