### PR TITLE
adding sam pluta manta live instrument

### PR DESCRIPTION
**Pull request by tiagmoraismorgado**

### CODE REVIEW

**Comment by crucialfelix** [comment]
1. It shouldn't be called by his name SamPluta
2. You should ask him first
3. The install instructions are a bit more complicated: https://github.com/spluta/LiveModularInstrument

Let's wait to see what he says first.  Hey Sam !  @spluta

**Comment by tiagmoraismorgado** [comment]
@crucialfelix  i agree. it's nice and polite to ask people first if we can use their stuff. however i think open source is open source. so the more we get people's stuff to intertwine and bind together. the more development we will achieve. and i think from a personal perspective, that this is not stealing. this promoting community awareness around a tool by one of the great supercollider developers out there. and for sure one of the greatest improvisers out there

**Comment by spluta** [comment]
Hey all,

Thanks for bringing this up Tiago. 
> It shouldn't be called by his name SamPluta
Hah. This is true. It is called the Live Modular Instrument.

> You should ask him first
I am not really clear on what exactly is being proposed. My goal for this software over the long-term is to make it more available for more people, so I think I am interested.
> The install instructions are a bit more complicated: https://github.com/spluta/LiveModularInstrument <https://github.com/spluta/LiveModularInstrument>At this time, the software is designed for my own personal use. I have made it available because I would love people steal ideas from it and maybe use it. 

I haven’t had time to 1) document the function of the software, 2) document how to create personalized classes for the software, and 3) make it easy to install. 

I always want to do these things, but I never seem to find the time to do them. I would need many months of free time to do this. :(

Just a side note, the software works with Manta, Lemur, and any Midi device, so it is far more than a Manta instrument.


Once I am clearer on what is being proposed, I would probably love to help make that happen.


Sam

**Comment by tiagmoraismorgado** [comment]
so, @spluta. your instrument goes along in the direction of stuff like steim software, at least in the sense that there are states in the program and in the overall way you map things. and it's easy use to use and make new stuff out of it. my main suggestion. once you can easily do all these things, it could turn out to be a good community project if: you can adapt it to be mapped to other controllers, and other sources. if people can integrate new modules easily and there's a community sense in sharing those modules. so, from my point of sight, it could work out to turn manta into something like this: http://ppooll.klingt.org/index.php/Main_Page furthermore, i think, but that's only my personal way of seeing things, that another really cool feature, would be, into a certain regard, or a certain extent, allowing these kinds of tools to intertwine with another tools (supercollider+max+csound+ableton, for an instance). well i can make things more specific. by now we can say to people: use it at your own risk. and take the suggestion you gave us for another kinds of things

**Comment by crucialfelix** [comment]
Just change it to LiveModularInstrument and we can merge it into the directory.

@spluta people can always install any github repo simply by `Quarks.install("https://github.com/spluta/LiveModularInstrument")` but it is also nice to add these to the directory so more people notice it.

**Pull request closed without merging**
