### PR TITLE
Add Faust.quark and ReaCollider

### PR DESCRIPTION
**Pull request by madskjeldgaard**

### CODE REVIEW

**Comment by dyfer** [comment]
Thanks! Cool projects!
I think we typically don't include `.quark` in the quark's name. Would you mind changing that? (i.e. `Faust.quark=https...` >> `Faust=https...`)

**Comment by dyfer** [comment]
Any update on this @madskjeldgaard ?

**Comment by dyfer** [comment]
@madskjeldgaard would you be willing to change the name as requested?

**Comment by dyfer** [comment]
@madskjeldgaard ping?

**Comment by LFSaw** [comment]
IMHO, it is a good idea to have a separation of FAUST and FAUST.quark as proposed by @madskjeldgaard. I'd vote for inclusion as is.

**Pull request merged**
