### PR TITLE
add EQui

### PR DESCRIPTION
**Pull request by telephon**
it is a useful library …

### CODE REVIEW

**Comment by dyfer** [comment]
We can add it if there's a .quark file in it.

**Comment by LFSaw** [comment]
I contacted the original author https://github.com/muellmusik/EQui/issues/1

**Comment by muellmusik** [comment]
Very happy for this! Please add!

**Comment by LFSaw** [comment]
great! the only thing missing still, is the quark file in your repository, @muellmusik.

**Comment by LFSaw** [comment]
please let me know, e.g. through a direct mention, when a quarks file is added, then I'm happy to approve and merge.

**Comment by muellmusik** [comment]
@LFSaw I’ll try to do it this week. Just got back from ICLC in Shanghai, so was pretty busy until today.

**Comment by LFSaw** [comment]
no worries, I just wanted to follow up on me being assigned reviewer by telephon :)

**Comment by muellmusik** [comment]
> no worries, I just wanted to follow up on me being assigned reviewer by telephon :)

I serious responsibility, no doubt!!

**Comment by muellmusik** [comment]
Okay, think I've done it now. Hopefully correctly.

**Comment by muellmusik** [comment]
> Okay, think I've done it now. Hopefully correctly.

@LFSaw

**Review by LFSaw — APPROVED** [review]

**Comment by LFSaw** [comment]
done. Thanks to all for this addition :)

**Comment by smoge** [comment]
Just tested it, it's really useful, I'll use it for sure)))  Thanks guys

**Comment by LFSaw** [comment]
mind to post an example here? I am a little baffled...

**Comment by smoge** [comment]
I'm a bit impressed how it is possible to scale it. Some fancy things are possible.

**Comment by muellmusik** [comment]
> mind to post an example here? I am a little baffled...

Sorry, looks like I never finished the help file! Will add something now...

**Comment by muellmusik** [comment]
@LFSaw I've added this to the help file. I discovered a couple of small issues, so you'll need to pull the latest source. Is this clearer?
```
//////// Basic functionality

(
SynthDef(\testEQui, {
	Out.ar(0, WhiteNoise.ar(0.1).equi);
}).add;
)

(
x = Synth(\testEQui);
e = EQui(target: x); // change the GUI; alt-drag changes q
)

p = e.value.postcs; // get an EQuiParams representing the current state, post compile string to the window

x.set(\midPeakGain, 6, \hiPeakGain, -6); // change values on synth
e.sync; // sync the EQui

e.valueAction = p; // reset to params stored in p, and update target

e.valueAction = EQuiParams(345.0, -15.0, 1, 250, 0, 1, 900.0, 16.25, 1, 3500, 0, 1, 2634.0, -24.0, 1); // set to some manually created params

x.free

//////// With an Array of UGens

x = { Saw.ar([120, 121], 0.1).equi }.play; // a stereo EQui
EQui(target: x);

x.free;

//////// Multiple EQuis in the same target

x = { [Saw.ar(120, 0.1).equi(prefix: "saw-"), GrayNoise.ar(0.1).equi(prefix: "noise-")] }.play; // a stereo EQui
(
EQui(target: x, prefix: "saw-");
EQui(target: x, prefix: "noise-");
)

x.free;

//////// With an Ndef

Ndef(\clipnoise, { ClipNoise.ar(0.1) }).play;

Ndef(\clipnoise).equi; // adds \filter -> equi at index 1000 by default

Ndef(\clipnoise).clear;
```

**Comment by LFSaw** [comment]
This is _really_ cool. Thanks a bunch!
I'll definitely use this a lot!

**Comment by muellmusik** [comment]
Thanks! Suggestions welcome!

**Pull request merged**
