### PR TITLE
Add NodeProxy-enhancements-SN quark

### PR DESCRIPTION
**Pull request by nuss**
This quark adds a NodeProxy:-seti method, modelled after the Synth:-seti method, and two additional NodeProxy roles, \seti and \setm.

### CODE REVIEW

**Comment by dyfer** [comment]
Hello @nuss 
Sorry for the delay.
Other quarks don't have `.git` in the URL, would you mind removing that for consistency?

**Comment by nuss** [comment]
Oh, sorry, I overlooked this little detail. Should be fixed now.

**Comment by dyfer** [comment]
Thanks!
I'm so sorry, I didn't notice when I looked at this before: we generally try to maintain alphabetical order in this file, would you mind doing that as well?

**Comment by dyfer** [comment]
Thanks!

**Pull request merged**
