### PR TITLE
add JSONlib

### PR DESCRIPTION
**Pull request by capital-G**
https://github.com/musikinformatik/JSONlib

Some additional JSON functionality for sclang

### CODE REVIEW

**Comment by dyfer** [comment]
I believe @telephon already added this? https://github.com/supercollider-quarks/quarks/commit/c6c44d10242f5cfdb909c716f3b741712c01dbb1

**Comment by capital-G** [comment]
Yes so this becomes obsolete - but thanks for the quick review :)

**Comment by telephon** [comment]
yes, sorry, an old habit.

**Comment by dyfer** [comment]
No worries! Just noted that this was already merged in.

**Comment by telephon** [comment]
It seems that the API quark does encoding, but not decoding. But there are some things that it cares for which we should consiuder (e.g. checking nans etc.).

**Pull request closed without merging**
